#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "AccountConfiguration" \
  --arg udid "$1" \
  '.udid = $udid
  |.skip_primary_setup_account_creation = false
  |.set_primary_setup_account_as_regular_user = false
  |.request_type = $request_type
  |.auto_setup_admin_accounts = [{"short_name": "groob", "full_name": "Groob G", "password_hash": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPjxkaWN0PjxrZXk+U0FMVEVELVNIQTUxMi1QQktERjI8L2tleT48ZGljdD48a2V5PmVudHJvcHk8L2tleT48ZGF0YT5oMjBhTG1YZ2NHSU1xMjc0OXJqS0tqMU4rWWFFN1NkWGM4cmFhZGkrTXg2TjZxanB1alhVNk5YQ1lEbUhDd29SdzdzSjJRMjVQYTcvSDZvWU01ZlF0Y2JxT1g5NnNSVlVjSVNGQVRSdEUvZytxOGRzUjZTdngxK0FTK0EvLzkrK0NQYTBlOWN3allRaWN6MTNtbmtyM1MwUCs0NUZVLzRWQUZIS3RubU96eFU9PC9kYXRhPjxrZXk+aXRlcmF0aW9uczwva2V5PjxpbnRlZ2VyPjMwNDg2PC9pbnRlZ2VyPjxrZXk+c2FsdDwva2V5PjxkYXRhPm1HNldHMldJQy9POGx0eDd3RUZJQ29USzZDbUNrbTNZWEhITWxUTW9rQmc9PC9kYXRhPjwvZGljdD48L2RpY3Q+PC9wbGlzdD4K"}]
  '|\
   curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
