#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "SetAutoAdminPassword" \
  --arg udid "$1" \
  '.udid = $udid
  |.request_type = $request_type
  |.guid = "FDCF8014-6754-49C2-B4C6-5A909217E827"
  |.password_hash = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPjxkaWN0PjxrZXk+U0FMVEVELVNIQTUxMi1QQktERjI8L2tleT48ZGljdD48a2V5PmVudHJvcHk8L2tleT48ZGF0YT5IcndrWU8xbmxRM1lPbm0yNWJJcU90bzRxNXNCMmd3blV5SWpoT29tYUtmcGZqd3hyVHZQV2J1M1U1ZHpqMVRZd3lGZ01aamg2Wlk3Vlh3OHJzTFNmblFBWDVvRWd1V2FwVmdZNmVheWJqSzUzd2tJTmpJREpLNzY2NVhhNU5rUFNUWGgrU1l3MTNGVnpJaDhUdXgzMFlsR2hDRk5jeVVlQXBUeWkwUUFkY3M9PC9kYXRhPjxrZXk+aXRlcmF0aW9uczwva2V5PjxpbnRlZ2VyPjM0ODExPC9pbnRlZ2VyPjxrZXk+c2FsdDwva2V5PjxkYXRhPjVOSmJPTS9WbkhtdFExdXNpeXFQdnJ1c05hMTNWK2JkQ2dxOWdSSllydVU9PC9kYXRhPjwvZGljdD48L2RpY3Q+PC9wbGlzdD4K"
  '|\
   curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
