redis:
    image: redis
    restart: always
    ports:
        - "6379:6379"

postgres:
    image: postgres
    restart: always
    environment:
        - POSTGRES_USER=micromdm
        - POSTGRES_PASSWORD=micromdm
        - POSTGRES_DB=micromdm
        - SSLMODE=disable
    ports:
        - "127.0.0.1:5432:5432"

scep:
    image: micromdm/scep
    restart: always
    ports:
      - "2016:8080"
    volumes:
      - ./.docker/depot:/depot