[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "v1.3.0"

[[override]]
  name = "github.com/go-kit/kit"
  version = "v0.7.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/groob/plist"
  branch = "master"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[override]]
  name = "github.com/micromdm/scep"
  branch = "master"

[[override]]
  branch = "sha256"
  name = "github.com/fullsailor/pkcs7"
  source = "github.com/groob/pkcs7"
