// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkin.proto

package checkinproto

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time                 int64             `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Command              *Command          `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Raw                  []byte            `protobuf:"bytes,4,opt,name=raw,proto3" json:"raw,omitempty"`
	Params               map[string]string `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkin_f106eb4ffaf2f7e3, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Event) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Event) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *Event) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type Command struct {
	MessageType          string             `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Topic                string             `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Udid                 string             `protobuf:"bytes,3,opt,name=udid,proto3" json:"udid,omitempty"`
	Authenticate         *Authenticate      `protobuf:"bytes,4,opt,name=authenticate,proto3" json:"authenticate,omitempty"`
	TokenUpdate          *TokenUpdate       `protobuf:"bytes,5,opt,name=token_update,json=tokenUpdate,proto3" json:"token_update,omitempty"`
	EnrollmentId         string             `protobuf:"bytes,6,opt,name=enrollment_id,json=enrollmentId,proto3" json:"enrollment_id,omitempty"`
	GetBootstrapToken    *GetBootstrapToken `protobuf:"bytes,7,opt,name=get_bootstrap_token,json=getBootstrapToken,proto3" json:"get_bootstrap_token,omitempty"`
	SetBootstrapToken    *SetBootstrapToken `protobuf:"bytes,8,opt,name=set_bootstrap_token,json=setBootstrapToken,proto3" json:"set_bootstrap_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkin_f106eb4ffaf2f7e3, []int{1}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *Command) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Command) GetUdid() string {
	if m != nil {
		return m.Udid
	}
	return ""
}

func (m *Command) GetAuthenticate() *Authenticate {
	if m != nil {
		return m.Authenticate
	}
	return nil
}

func (m *Command) GetTokenUpdate() *TokenUpdate {
	if m != nil {
		return m.TokenUpdate
	}
	return nil
}

func (m *Command) GetEnrollmentId() string {
	if m != nil {
		return m.EnrollmentId
	}
	return ""
}

func (m *Command) GetGetBootstrapToken() *GetBootstrapToken {
	if m != nil {
		return m.GetBootstrapToken
	}
	return nil
}

func (m *Command) GetSetBootstrapToken() *SetBootstrapToken {
	if m != nil {
		return m.SetBootstrapToken
	}
	return nil
}

type Authenticate struct {
	OsVersion            string   `protobuf:"bytes,1,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	BuildVersion         string   `protobuf:"bytes,2,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	ProductName          string   `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	SerialNumber         string   `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Imei                 string   `protobuf:"bytes,5,opt,name=imei,proto3" json:"imei,omitempty"`
	Meid                 string   `protobuf:"bytes,6,opt,name=meid,proto3" json:"meid,omitempty"`
	DeviceName           string   `protobuf:"bytes,7,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Challenge            []byte   `protobuf:"bytes,8,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Model                string   `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	ModelName            string   `protobuf:"bytes,10,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Authenticate) Reset()         { *m = Authenticate{} }
func (m *Authenticate) String() string { return proto.CompactTextString(m) }
func (*Authenticate) ProtoMessage()    {}
func (*Authenticate) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkin_f106eb4ffaf2f7e3, []int{2}
}
func (m *Authenticate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authenticate.Unmarshal(m, b)
}
func (m *Authenticate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authenticate.Marshal(b, m, deterministic)
}
func (dst *Authenticate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authenticate.Merge(dst, src)
}
func (m *Authenticate) XXX_Size() int {
	return xxx_messageInfo_Authenticate.Size(m)
}
func (m *Authenticate) XXX_DiscardUnknown() {
	xxx_messageInfo_Authenticate.DiscardUnknown(m)
}

var xxx_messageInfo_Authenticate proto.InternalMessageInfo

func (m *Authenticate) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *Authenticate) GetBuildVersion() string {
	if m != nil {
		return m.BuildVersion
	}
	return ""
}

func (m *Authenticate) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Authenticate) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Authenticate) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *Authenticate) GetMeid() string {
	if m != nil {
		return m.Meid
	}
	return ""
}

func (m *Authenticate) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *Authenticate) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

func (m *Authenticate) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Authenticate) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

type TokenUpdate struct {
	Token                 []byte   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PushMagic             string   `protobuf:"bytes,2,opt,name=push_magic,json=pushMagic,proto3" json:"push_magic,omitempty"`
	UnlockToken           []byte   `protobuf:"bytes,3,opt,name=unlock_token,json=unlockToken,proto3" json:"unlock_token,omitempty"`
	AwaitingConfiguration bool     `protobuf:"varint,4,opt,name=awaiting_configuration,json=awaitingConfiguration,proto3" json:"awaiting_configuration,omitempty"`
	UserId                string   `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserLongName          string   `protobuf:"bytes,6,opt,name=user_long_name,json=userLongName,proto3" json:"user_long_name,omitempty"`
	UserShortName         string   `protobuf:"bytes,7,opt,name=user_short_name,json=userShortName,proto3" json:"user_short_name,omitempty"`
	NotOnConsole          bool     `protobuf:"varint,8,opt,name=not_on_console,json=notOnConsole,proto3" json:"not_on_console,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *TokenUpdate) Reset()         { *m = TokenUpdate{} }
func (m *TokenUpdate) String() string { return proto.CompactTextString(m) }
func (*TokenUpdate) ProtoMessage()    {}
func (*TokenUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkin_f106eb4ffaf2f7e3, []int{3}
}
func (m *TokenUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenUpdate.Unmarshal(m, b)
}
func (m *TokenUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenUpdate.Marshal(b, m, deterministic)
}
func (dst *TokenUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenUpdate.Merge(dst, src)
}
func (m *TokenUpdate) XXX_Size() int {
	return xxx_messageInfo_TokenUpdate.Size(m)
}
func (m *TokenUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TokenUpdate proto.InternalMessageInfo

func (m *TokenUpdate) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *TokenUpdate) GetPushMagic() string {
	if m != nil {
		return m.PushMagic
	}
	return ""
}

func (m *TokenUpdate) GetUnlockToken() []byte {
	if m != nil {
		return m.UnlockToken
	}
	return nil
}

func (m *TokenUpdate) GetAwaitingConfiguration() bool {
	if m != nil {
		return m.AwaitingConfiguration
	}
	return false
}

func (m *TokenUpdate) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TokenUpdate) GetUserLongName() string {
	if m != nil {
		return m.UserLongName
	}
	return ""
}

func (m *TokenUpdate) GetUserShortName() string {
	if m != nil {
		return m.UserShortName
	}
	return ""
}

func (m *TokenUpdate) GetNotOnConsole() bool {
	if m != nil {
		return m.NotOnConsole
	}
	return false
}

type GetBootstrapToken struct {
	GAwaitingConfiguration bool     `protobuf:"varint,1,opt,name=g_awaiting_configuration,json=gAwaitingConfiguration,proto3" json:"g_awaiting_configuration,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *GetBootstrapToken) Reset()         { *m = GetBootstrapToken{} }
func (m *GetBootstrapToken) String() string { return proto.CompactTextString(m) }
func (*GetBootstrapToken) ProtoMessage()    {}
func (*GetBootstrapToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkin_f106eb4ffaf2f7e3, []int{4}
}
func (m *GetBootstrapToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBootstrapToken.Unmarshal(m, b)
}
func (m *GetBootstrapToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBootstrapToken.Marshal(b, m, deterministic)
}
func (dst *GetBootstrapToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBootstrapToken.Merge(dst, src)
}
func (m *GetBootstrapToken) XXX_Size() int {
	return xxx_messageInfo_GetBootstrapToken.Size(m)
}
func (m *GetBootstrapToken) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBootstrapToken.DiscardUnknown(m)
}

var xxx_messageInfo_GetBootstrapToken proto.InternalMessageInfo

func (m *GetBootstrapToken) GetGAwaitingConfiguration() bool {
	if m != nil {
		return m.GAwaitingConfiguration
	}
	return false
}

type SetBootstrapToken struct {
	BootstrapToken         []byte   `protobuf:"bytes,1,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	SAwaitingConfiguration bool     `protobuf:"varint,2,opt,name=s_awaiting_configuration,json=sAwaitingConfiguration,proto3" json:"s_awaiting_configuration,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *SetBootstrapToken) Reset()         { *m = SetBootstrapToken{} }
func (m *SetBootstrapToken) String() string { return proto.CompactTextString(m) }
func (*SetBootstrapToken) ProtoMessage()    {}
func (*SetBootstrapToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkin_f106eb4ffaf2f7e3, []int{5}
}
func (m *SetBootstrapToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBootstrapToken.Unmarshal(m, b)
}
func (m *SetBootstrapToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBootstrapToken.Marshal(b, m, deterministic)
}
func (dst *SetBootstrapToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBootstrapToken.Merge(dst, src)
}
func (m *SetBootstrapToken) XXX_Size() int {
	return xxx_messageInfo_SetBootstrapToken.Size(m)
}
func (m *SetBootstrapToken) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBootstrapToken.DiscardUnknown(m)
}

var xxx_messageInfo_SetBootstrapToken proto.InternalMessageInfo

func (m *SetBootstrapToken) GetBootstrapToken() []byte {
	if m != nil {
		return m.BootstrapToken
	}
	return nil
}

func (m *SetBootstrapToken) GetSAwaitingConfiguration() bool {
	if m != nil {
		return m.SAwaitingConfiguration
	}
	return false
}

func init() {
	proto.RegisterType((*Event)(nil), "checkinproto.Event")
	proto.RegisterMapType((map[string]string)(nil), "checkinproto.Event.ParamsEntry")
	proto.RegisterType((*Command)(nil), "checkinproto.Command")
	proto.RegisterType((*Authenticate)(nil), "checkinproto.Authenticate")
	proto.RegisterType((*TokenUpdate)(nil), "checkinproto.TokenUpdate")
	proto.RegisterType((*GetBootstrapToken)(nil), "checkinproto.GetBootstrapToken")
	proto.RegisterType((*SetBootstrapToken)(nil), "checkinproto.SetBootstrapToken")
}

func init() { proto.RegisterFile("checkin.proto", fileDescriptor_checkin_f106eb4ffaf2f7e3) }

var fileDescriptor_checkin_f106eb4ffaf2f7e3 = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xff, 0x4e, 0xdb, 0x48,
	0x10, 0x96, 0x13, 0x92, 0xe0, 0xb1, 0x09, 0xc7, 0xde, 0xc1, 0xf9, 0xd0, 0x9d, 0x08, 0x39, 0x74,
	0x97, 0xbf, 0x72, 0x12, 0xa7, 0xaa, 0xb4, 0xaa, 0x2a, 0x51, 0x84, 0x2a, 0xa4, 0x02, 0x95, 0xa1,
	0xfd, 0xd7, 0xda, 0xd8, 0x5b, 0x67, 0x15, 0x7b, 0xd7, 0xf2, 0xae, 0x83, 0xf2, 0x2c, 0x7d, 0x82,
	0xbe, 0x40, 0x1f, 0xa8, 0x4f, 0x52, 0xed, 0xac, 0x03, 0xf9, 0xc5, 0x7f, 0x33, 0xdf, 0x7e, 0xfe,
	0x66, 0xe6, 0x9b, 0x31, 0xec, 0xc4, 0x63, 0x16, 0x4f, 0xb8, 0x18, 0x16, 0xa5, 0xd4, 0x92, 0xf8,
	0x75, 0x8a, 0x59, 0xff, 0x87, 0x03, 0xad, 0xcb, 0x29, 0x13, 0x9a, 0x74, 0xa1, 0xc1, 0x93, 0xc0,
	0xe9, 0x39, 0x03, 0x37, 0x6c, 0xf0, 0x84, 0x10, 0xd8, 0xd2, 0x3c, 0x67, 0x41, 0xa3, 0xe7, 0x0c,
	0x9a, 0x21, 0xc6, 0xe4, 0x3f, 0xe8, 0xc4, 0x32, 0xcf, 0xa9, 0x48, 0x82, 0x66, 0xcf, 0x19, 0x78,
	0xa7, 0xfb, 0xc3, 0x45, 0xb5, 0xe1, 0x85, 0x7d, 0x0c, 0xe7, 0x2c, 0xf2, 0x0b, 0x34, 0x4b, 0xfa,
	0x10, 0x6c, 0xf5, 0x9c, 0x81, 0x1f, 0x9a, 0x90, 0xbc, 0x84, 0x76, 0x41, 0x4b, 0x9a, 0xab, 0xa0,
	0xd5, 0x6b, 0x0e, 0xbc, 0xd3, 0xa3, 0x65, 0x05, 0xec, 0x65, 0xf8, 0x11, 0x19, 0x97, 0x42, 0x97,
	0xb3, 0xb0, 0xa6, 0x1f, 0xbe, 0x02, 0x6f, 0x01, 0x36, 0xca, 0x13, 0x36, 0xab, 0xfb, 0x35, 0x21,
	0xf9, 0x0d, 0x5a, 0x53, 0x9a, 0x55, 0xb6, 0x63, 0x37, 0xb4, 0xc9, 0xeb, 0xc6, 0x99, 0xd3, 0xff,
	0xda, 0x84, 0x4e, 0xdd, 0x1a, 0x39, 0x06, 0x3f, 0x67, 0x4a, 0xd1, 0x94, 0x45, 0x7a, 0x56, 0xb0,
	0x5a, 0xc0, 0xab, 0xb1, 0xfb, 0x59, 0xc1, 0x8c, 0x90, 0x96, 0x05, 0x8f, 0xe7, 0x42, 0x98, 0x18,
	0x3f, 0xaa, 0x84, 0xdb, 0xc1, 0xdd, 0x10, 0x63, 0xf2, 0x16, 0x7c, 0x5a, 0xe9, 0x31, 0x13, 0x9a,
	0xc7, 0x54, 0x33, 0x9c, 0xd3, 0x3b, 0x3d, 0x5c, 0x1e, 0xe9, 0x7c, 0x81, 0x11, 0x2e, 0xf1, 0xc9,
	0x1b, 0xf0, 0xb5, 0x9c, 0x30, 0x11, 0x55, 0x45, 0x62, 0xbe, 0x6f, 0xe1, 0xf7, 0x7f, 0x2c, 0x7f,
	0x7f, 0x6f, 0x18, 0x9f, 0x90, 0x10, 0x7a, 0xfa, 0x29, 0x21, 0x7f, 0xc3, 0x0e, 0x13, 0xa5, 0xcc,
	0xb2, 0x9c, 0x09, 0x1d, 0xf1, 0x24, 0x68, 0x63, 0x6b, 0xfe, 0x13, 0x78, 0x95, 0x90, 0x5b, 0xf8,
	0x35, 0x65, 0x3a, 0x1a, 0x49, 0xa9, 0x95, 0x2e, 0x69, 0x11, 0xa1, 0x42, 0xd0, 0xc1, 0x4a, 0x2b,
	0xe6, 0xbf, 0x67, 0xfa, 0xdd, 0x9c, 0x87, 0x55, 0xc3, 0xbd, 0x74, 0x15, 0x32, 0x82, 0x6a, 0x83,
	0xe0, 0xf6, 0x26, 0xc1, 0xbb, 0x75, 0x41, 0xb5, 0x0a, 0xf5, 0xbf, 0x37, 0xc0, 0x5f, 0xf4, 0x88,
	0xfc, 0x05, 0x20, 0x55, 0x34, 0x65, 0xa5, 0xe2, 0x52, 0xd4, 0x0b, 0x72, 0xa5, 0xfa, 0x6c, 0x01,
	0x33, 0xf6, 0xa8, 0xe2, 0x59, 0xf2, 0xc8, 0xb0, 0x6b, 0xf2, 0x11, 0x9c, 0x93, 0x8e, 0xc1, 0x2f,
	0x4a, 0x99, 0x54, 0xb1, 0x8e, 0x04, 0xcd, 0x59, 0xbd, 0x35, 0xaf, 0xc6, 0x6e, 0x68, 0x8e, 0xf6,
	0x29, 0x56, 0x72, 0x9a, 0x45, 0xa2, 0xca, 0x47, 0xac, 0xc4, 0xed, 0xb9, 0xa1, 0x6f, 0xc1, 0x1b,
	0xc4, 0xcc, 0xd6, 0x79, 0xce, 0x38, 0x6e, 0xc6, 0x0d, 0x31, 0x36, 0x58, 0xce, 0x1e, 0xed, 0xc6,
	0x98, 0x1c, 0x81, 0x97, 0xb0, 0x29, 0x8f, 0x99, 0x2d, 0xd7, 0xc1, 0x27, 0xb0, 0x10, 0x56, 0xfb,
	0x13, 0xdc, 0x78, 0x4c, 0xb3, 0x8c, 0x89, 0x94, 0xa1, 0x59, 0x7e, 0xf8, 0x04, 0x98, 0x93, 0xcb,
	0x65, 0xc2, 0xb2, 0xc0, 0xb5, 0x27, 0x87, 0x89, 0x31, 0x02, 0x03, 0xab, 0x09, 0xd6, 0x08, 0x44,
	0x8c, 0x64, 0xff, 0x5b, 0x03, 0xbc, 0x85, 0xe3, 0xb0, 0x77, 0x6b, 0x76, 0xe1, 0xa0, 0xbc, 0x4d,
	0x8c, 0x48, 0x51, 0xa9, 0x71, 0x94, 0xd3, 0xf4, 0xf1, 0xa4, 0x5d, 0x83, 0x5c, 0x1b, 0xc0, 0x18,
	0x55, 0x89, 0x4c, 0xc6, 0x93, 0x7a, 0x8f, 0x4d, 0xfc, 0xd6, 0xb3, 0x98, 0xdd, 0xf8, 0x0b, 0x38,
	0xa0, 0x0f, 0x94, 0x6b, 0x2e, 0xd2, 0x28, 0x96, 0xe2, 0x0b, 0x4f, 0xab, 0x92, 0x6a, 0xe3, 0xbc,
	0x71, 0x6c, 0x3b, 0xdc, 0x9f, 0xbf, 0x5e, 0x2c, 0x3e, 0x92, 0xdf, 0xa1, 0x53, 0x29, 0x56, 0x9a,
	0xc3, 0xb4, 0xee, 0xb5, 0x4d, 0x7a, 0x95, 0x90, 0x13, 0xe8, 0xe2, 0x43, 0x26, 0x45, 0x6a, 0x47,
	0xab, 0x0f, 0xd7, 0xa0, 0x1f, 0xa4, 0x48, 0xd1, 0xb0, 0x7f, 0x60, 0x17, 0x59, 0x6a, 0x2c, 0x4b,
	0xbd, 0xe8, 0xea, 0x8e, 0x81, 0xef, 0x0c, 0x8a, 0xbc, 0x13, 0xe8, 0x0a, 0xa9, 0x23, 0x29, 0x4c,
	0x6f, 0x4a, 0x66, 0xd6, 0xdd, 0xed, 0xd0, 0x17, 0x52, 0xdf, 0x8a, 0x0b, 0x8b, 0xf5, 0xaf, 0x61,
	0x6f, 0xed, 0xba, 0xc9, 0x19, 0x04, 0x69, 0xf4, 0xcc, 0x68, 0x0e, 0x8a, 0x1c, 0xa4, 0xe7, 0x9b,
	0x66, 0xeb, 0x4f, 0x61, 0x6f, 0xed, 0xb6, 0xc9, 0xbf, 0xb0, 0xbb, 0xfa, 0x57, 0xd8, 0x4d, 0x74,
	0x47, 0x6b, 0x75, 0xd5, 0x73, 0x75, 0x1b, 0xb6, 0xae, 0xda, 0x58, 0x77, 0xd4, 0xc6, 0xff, 0xea,
	0xff, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x2c, 0x9c, 0x1e, 0xd4, 0x05, 0x00, 0x00,
}
