version: 2
jobs:
  build-go1.10:
    docker:
        - image: golang:1.10
    working_directory: /go/src/github.com/micromdm/micromdm
    steps: &steps
      - checkout
      - run: make deps
      - run: make test
      - run: make

workflows:
  version: 2
  build:
    jobs:
      - build-go1.10
