version: 2
jobs:
  build-go1.11:
    docker:
        - image: golang:1.11
        - image: postgres:9.6
          environment:
            POSTGRES_DB: micromdm
            POSTGRES_USER: micromdm
            POSTGRES_PASSWORD: micromdm

    working_directory: /go/src/github.com/micromdm/micromdm
    steps: &steps
      - checkout
      - run: apt-get update -y && apt-get install postgresql-client -y
      - run: make deps
      - run: GO111MODULE=on go install github.com/pressly/goose/cmd/goose
      - run: make db-reset-test
      - run: make db-migrate-test
      - run: make test
      - run: make

workflows:
  version: 2
  build:
    jobs:
      - build-go1.11
