#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "InstallApplication" \
  --arg udid "$1" \
  --arg identifier "ch.abacus.abaclock.client2" \
  '.udid = $udid
  |.request_type = $request_type
  |.itunes_store_id = 1301278477
  |.management_flags = 1
  |.configuration = { "vpnuuid": $udid, "udid": $udid }
  |.attributes = { "vpnuuid": $udid, "udid": $udid }
  |.change_management_state = "Managed"
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
