#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n -c \
  --arg request_type "ManagedApplicationConfiguration" \
  --arg udid "$1" \
  '.udid = $udid 
  |.request_type = $request_type
  |.identifiers = [ "ch.abacus.abaclock.client2" ]
  '