#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "RequestMirroring" \
  --arg udid "$1" \
  --arg destination_device_id "$2" \
  '.udid = $udid
  |.destination_device_id = $destination_device_id 
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
