#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "ScheduleOSUpdate" \
  --arg udid "$1" \
  --arg install_action "$2" \
  '.udid = $udid 
  |.request_type = $request_type
  |.updates = [
      .install_action = $install_action
      ]
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
