#!/bin/bash

# Documentation:
# The configuration values must be provided to $3 must be a property list with the key/values for the configuration dictionary.
# Example:
#
# <?xml version="1.0" encoding="UTF-8"?>
# <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
# <plist version="1.0">
#   <dict>
#     <key>baz</key>
#     <string>qux</string>
#     <key>count</key>
#     <integer>1</integer>
#     <key>foo</key>
#     <string>bar</string>
#   </dict>
# </plist>


source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "Settings" \
  --arg udid "$1" \
  --arg identifier "$2" \
  --arg filename "$3" \
  --arg payload "$(cat $3|openssl base64 -A)" \
 '.udid = $udid 
  |.request_type = $request_type
  |.settings = [
  	{ "item": "ApplicationConfiguration", "identifier": $identifier, "configuration": $payload } ]
  '|\
  curl $CURL_OPTS \
    -H "Content-Type: application/json" \
    -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-