#!/bin/bash

# Documentation:
# The configuration values must be provided to $3 must be a property list with the key/values for the configuration dictionary.
# Example:
#
# <?xml version="1.0" encoding="UTF-8"?>
# <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
# <plist version="1.0">
#   <dict>
#     <key>baz</key>
#     <string>qux</string>
#     <key>count</key>
#     <integer>1</integer>
#     <key>foo</key>
#     <string>bar</string>
#   </dict>
# </plist>


source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "Settings" \
  --arg udid "$1" \
  --arg identifier "$2" \
  --arg filename "$3" \
  --arg payload "$(cat $3|openssl base64 -A)" \
 '.udid = $udid 
  |.request_type = $request_type
  |.settings = [
  	{ "item": "ApplicationConfiguration", "identifier": $identifier, "configuration": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgogIDxkaWN0PgogICAgPGtleT5iYXo8L2tleT4KICAgIDxzdHJpbmc+cXV4PC9zdHJpbmc+CiAgICA8a2V5PmNvdW50PC9rZXk+CiAgICA8aW50ZWdlcj4xPC9pbnRlZ2VyPgogICAgPGtleT5mb288L2tleT4KICAgIDxzdHJpbmc+YmFyPC9zdHJpbmc+CiAgPC9kaWN0Pgo8L3BsaXN0Pgo=" }
  ]
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-

#echo "$(cat $3|openssl base64 -A)"
