// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device.proto

package deviceproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device struct {
	Uuid                   string   `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Udid                   string   `protobuf:"bytes,2,opt,name=udid" json:"udid,omitempty"`
	SerialNumber           string   `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
	OsVersion              string   `protobuf:"bytes,4,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	BuildVersion           string   `protobuf:"bytes,5,opt,name=build_version,json=buildVersion" json:"build_version,omitempty"`
	ProductName            string   `protobuf:"bytes,6,opt,name=product_name,json=productName" json:"product_name,omitempty"`
	Imei                   string   `protobuf:"bytes,7,opt,name=imei" json:"imei,omitempty"`
	Meid                   string   `protobuf:"bytes,8,opt,name=meid" json:"meid,omitempty"`
	Token                  string   `protobuf:"bytes,9,opt,name=token" json:"token,omitempty"`
	PushMagic              string   `protobuf:"bytes,10,opt,name=push_magic,json=pushMagic" json:"push_magic,omitempty"`
	MdmTopic               string   `protobuf:"bytes,11,opt,name=mdm_topic,json=mdmTopic" json:"mdm_topic,omitempty"`
	UnlockToken            string   `protobuf:"bytes,12,opt,name=unlock_token,json=unlockToken" json:"unlock_token,omitempty"`
	Enrolled               bool     `protobuf:"varint,13,opt,name=enrolled" json:"enrolled,omitempty"`
	AwaitingConfiguration  bool     `protobuf:"varint,14,opt,name=awaiting_configuration,json=awaitingConfiguration" json:"awaiting_configuration,omitempty"`
	DeviceName             string   `protobuf:"bytes,15,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	Model                  string   `protobuf:"bytes,16,opt,name=model" json:"model,omitempty"`
	ModelName              string   `protobuf:"bytes,17,opt,name=model_name,json=modelName" json:"model_name,omitempty"`
	Description            string   `protobuf:"bytes,18,opt,name=description" json:"description,omitempty"`
	Color                  string   `protobuf:"bytes,19,opt,name=color" json:"color,omitempty"`
	AssetTag               string   `protobuf:"bytes,20,opt,name=asset_tag,json=assetTag" json:"asset_tag,omitempty"`
	DepDevice              bool     `protobuf:"varint,21,opt,name=dep_device,json=depDevice" json:"dep_device,omitempty"`
	DepProfileStatus       string   `protobuf:"bytes,22,opt,name=dep_profile_status,json=depProfileStatus" json:"dep_profile_status,omitempty"`
	DepProfileUuid         string   `protobuf:"bytes,23,opt,name=dep_profile_uuid,json=depProfileUuid" json:"dep_profile_uuid,omitempty"`
	DepProfileAssignTime   int64    `protobuf:"varint,24,opt,name=dep_profile_assign_time,json=depProfileAssignTime" json:"dep_profile_assign_time,omitempty"`
	DepProfilePushTime     int64    `protobuf:"varint,25,opt,name=dep_profile_push_time,json=depProfilePushTime" json:"dep_profile_push_time,omitempty"`
	DepProfileAssignedDate int64    `protobuf:"varint,26,opt,name=dep_profile_assigned_date,json=depProfileAssignedDate" json:"dep_profile_assigned_date,omitempty"`
	DepProfileAssignedBy   string   `protobuf:"bytes,27,opt,name=dep_profile_assigned_by,json=depProfileAssignedBy" json:"dep_profile_assigned_by,omitempty"`
	LastSeen               int64    `protobuf:"varint,28,opt,name=last_seen,json=lastSeen" json:"last_seen,omitempty"`
	LastQueryResponse      []byte   `protobuf:"bytes,29,opt,name=last_query_response,json=lastQueryResponse,proto3" json:"last_query_response,omitempty"`
	DeviceCert             []byte   `protobuf:"bytes,30,opt,name=device_cert,json=deviceCert,proto3" json:"device_cert,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_ebfc7a102939d09a, []int{0}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (dst *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(dst, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Device) GetUdid() string {
	if m != nil {
		return m.Udid
	}
	return ""
}

func (m *Device) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Device) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *Device) GetBuildVersion() string {
	if m != nil {
		return m.BuildVersion
	}
	return ""
}

func (m *Device) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Device) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *Device) GetMeid() string {
	if m != nil {
		return m.Meid
	}
	return ""
}

func (m *Device) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Device) GetPushMagic() string {
	if m != nil {
		return m.PushMagic
	}
	return ""
}

func (m *Device) GetMdmTopic() string {
	if m != nil {
		return m.MdmTopic
	}
	return ""
}

func (m *Device) GetUnlockToken() string {
	if m != nil {
		return m.UnlockToken
	}
	return ""
}

func (m *Device) GetEnrolled() bool {
	if m != nil {
		return m.Enrolled
	}
	return false
}

func (m *Device) GetAwaitingConfiguration() bool {
	if m != nil {
		return m.AwaitingConfiguration
	}
	return false
}

func (m *Device) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Device) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *Device) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Device) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Device) GetAssetTag() string {
	if m != nil {
		return m.AssetTag
	}
	return ""
}

func (m *Device) GetDepDevice() bool {
	if m != nil {
		return m.DepDevice
	}
	return false
}

func (m *Device) GetDepProfileStatus() string {
	if m != nil {
		return m.DepProfileStatus
	}
	return ""
}

func (m *Device) GetDepProfileUuid() string {
	if m != nil {
		return m.DepProfileUuid
	}
	return ""
}

func (m *Device) GetDepProfileAssignTime() int64 {
	if m != nil {
		return m.DepProfileAssignTime
	}
	return 0
}

func (m *Device) GetDepProfilePushTime() int64 {
	if m != nil {
		return m.DepProfilePushTime
	}
	return 0
}

func (m *Device) GetDepProfileAssignedDate() int64 {
	if m != nil {
		return m.DepProfileAssignedDate
	}
	return 0
}

func (m *Device) GetDepProfileAssignedBy() string {
	if m != nil {
		return m.DepProfileAssignedBy
	}
	return ""
}

func (m *Device) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *Device) GetLastQueryResponse() []byte {
	if m != nil {
		return m.LastQueryResponse
	}
	return nil
}

func (m *Device) GetDeviceCert() []byte {
	if m != nil {
		return m.DeviceCert
	}
	return nil
}

func init() {
	proto.RegisterType((*Device)(nil), "deviceproto.Device")
}

func init() { proto.RegisterFile("device.proto", fileDescriptor_device_ebfc7a102939d09a) }

var fileDescriptor_device_ebfc7a102939d09a = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0x4f, 0x53, 0x13, 0x31,
	0x14, 0x9f, 0x0a, 0xad, 0xdb, 0xb4, 0x60, 0x09, 0x6d, 0x09, 0x20, 0x5a, 0xf5, 0xd2, 0x83, 0xc3,
	0x8c, 0xe3, 0x70, 0xf0, 0xa8, 0x70, 0x95, 0xc1, 0x52, 0xbd, 0x66, 0xd2, 0xcd, 0x63, 0xc9, 0xb0,
	0x49, 0xd6, 0x24, 0x8b, 0xd3, 0x6f, 0xe2, 0xc7, 0x75, 0xf2, 0xb2, 0xd0, 0x1d, 0xe1, 0x96, 0xf7,
	0xfb, 0xf3, 0xfe, 0xed, 0x9b, 0x25, 0x43, 0x09, 0xf7, 0x2a, 0x87, 0xd3, 0xca, 0xd9, 0x60, 0xe9,
	0x20, 0x45, 0x18, 0xbc, 0xff, 0x9b, 0x91, 0xde, 0x05, 0xc6, 0x94, 0x92, 0xed, 0xba, 0x56, 0x92,
	0x75, 0x66, 0x9d, 0x79, 0x7f, 0x81, 0x6f, 0xc4, 0xa4, 0x92, 0xec, 0x45, 0x83, 0x49, 0x25, 0xe9,
	0x07, 0xb2, 0xe3, 0xc1, 0x29, 0x51, 0x72, 0x53, 0xeb, 0x15, 0x38, 0xb6, 0x85, 0xe4, 0x30, 0x81,
	0x97, 0x88, 0xd1, 0x13, 0x42, 0xac, 0xe7, 0xf7, 0xe0, 0xbc, 0xb2, 0x86, 0x6d, 0xa3, 0xa2, 0x6f,
	0xfd, 0xaf, 0x04, 0xc4, 0x1c, 0xab, 0x5a, 0x95, 0xf2, 0x51, 0xd1, 0x4d, 0x39, 0x10, 0x7c, 0x10,
	0xbd, 0x23, 0xc3, 0xca, 0x59, 0x59, 0xe7, 0x81, 0x1b, 0xa1, 0x81, 0xf5, 0x50, 0x33, 0x68, 0xb0,
	0x4b, 0xa1, 0xb1, 0x67, 0xa5, 0x41, 0xb1, 0x97, 0xa9, 0xbf, 0xf8, 0x8e, 0x98, 0x06, 0x25, 0x59,
	0x96, 0xb0, 0xf8, 0xa6, 0x63, 0xd2, 0x0d, 0xf6, 0x0e, 0x0c, 0xeb, 0x23, 0x98, 0x82, 0xd8, 0x64,
	0x55, 0xfb, 0x5b, 0xae, 0x45, 0xa1, 0x72, 0x46, 0x52, 0x93, 0x11, 0xf9, 0x1e, 0x01, 0x7a, 0x4c,
	0xfa, 0x5a, 0x6a, 0x1e, 0x6c, 0xa5, 0x72, 0x36, 0x40, 0x36, 0xd3, 0x52, 0x2f, 0x63, 0x1c, 0x9b,
	0xab, 0x4d, 0x69, 0xf3, 0x3b, 0x9e, 0x12, 0x0f, 0x53, 0x73, 0x09, 0x5b, 0x62, 0xfa, 0x23, 0x92,
	0x81, 0x71, 0xb6, 0x2c, 0x41, 0xb2, 0x9d, 0x59, 0x67, 0x9e, 0x2d, 0x1e, 0x63, 0x7a, 0x46, 0xa6,
	0xe2, 0x8f, 0x50, 0x41, 0x99, 0x82, 0xe7, 0xd6, 0xdc, 0xa8, 0xa2, 0x76, 0x22, 0xc4, 0x4d, 0xec,
	0xa2, 0x72, 0xf2, 0xc0, 0x9e, 0xb7, 0x49, 0xfa, 0x96, 0x34, 0x5f, 0x2f, 0x6d, 0xe4, 0x15, 0x16,
	0x25, 0x09, 0xc2, 0x85, 0x8c, 0x49, 0x57, 0x5b, 0x09, 0x25, 0x1b, 0xa5, 0x41, 0x31, 0x88, 0x83,
	0xe2, 0x23, 0xb9, 0xf6, 0xd2, 0xa0, 0x88, 0xa0, 0x69, 0x16, 0xb3, 0xfa, 0xdc, 0xa9, 0x0a, 0x3b,
	0xa0, 0x69, 0x94, 0x16, 0x14, 0xd3, 0xe6, 0xb6, 0xb4, 0x8e, 0xed, 0xa7, 0xb4, 0x18, 0xc4, 0x05,
	0x09, 0xef, 0x21, 0xf0, 0x20, 0x0a, 0x36, 0x4e, 0x0b, 0x42, 0x60, 0x29, 0x8a, 0x58, 0x53, 0x42,
	0xc5, 0x53, 0x6f, 0x6c, 0x82, 0x53, 0xf5, 0x25, 0x54, 0xcd, 0xb5, 0x7d, 0x24, 0x34, 0xd2, 0x95,
	0xb3, 0x37, 0xaa, 0x04, 0xee, 0x83, 0x08, 0xb5, 0x67, 0x53, 0x4c, 0x32, 0x92, 0x50, 0x5d, 0x25,
	0xe2, 0x1a, 0x71, 0x3a, 0x27, 0xa3, 0xb6, 0x1a, 0xef, 0xf4, 0x00, 0xb5, 0xbb, 0x1b, 0xed, 0xcf,
	0x78, 0xb1, 0x67, 0xe4, 0xa0, 0xad, 0x14, 0xde, 0xab, 0xc2, 0xf0, 0xa0, 0x34, 0x30, 0x36, 0xeb,
	0xcc, 0xb7, 0x16, 0xe3, 0x8d, 0xe1, 0x2b, 0x92, 0x4b, 0xa5, 0x81, 0x7e, 0x22, 0x93, 0xb6, 0x0d,
	0xcf, 0x02, 0x4d, 0x87, 0x68, 0xa2, 0x1b, 0xd3, 0x55, 0xed, 0x6f, 0xd1, 0xf2, 0x85, 0x1c, 0x3e,
	0xad, 0x04, 0x92, 0x4b, 0x11, 0x80, 0x1d, 0xa1, 0x6d, 0xfa, 0x7f, 0x2d, 0x90, 0x17, 0x22, 0xc0,
	0xf3, 0x4d, 0x82, 0xe4, 0xab, 0x35, 0x3b, 0xc6, 0xa9, 0xc6, 0x4f, 0x8d, 0xdf, 0xd6, 0x71, 0xdf,
	0xa5, 0xf0, 0x81, 0x7b, 0x00, 0xc3, 0x5e, 0x63, 0x85, 0x2c, 0x02, 0xd7, 0x00, 0x86, 0x9e, 0x92,
	0x7d, 0x24, 0x7f, 0xd7, 0xe0, 0xd6, 0xdc, 0x81, 0xaf, 0xac, 0xf1, 0xc0, 0x4e, 0x66, 0x9d, 0xf9,
	0x70, 0xb1, 0x17, 0xa9, 0x1f, 0x91, 0x59, 0x34, 0x44, 0xeb, 0x94, 0x72, 0x70, 0x81, 0xbd, 0x41,
	0x5d, 0x73, 0x4a, 0xe7, 0xe0, 0xc2, 0xaa, 0x87, 0x7f, 0x88, 0xcf, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x5c, 0x79, 0x24, 0xb0, 0x3e, 0x04, 0x00, 0x00,
}
